### ISSUE TITLE
Bug: 리프레쉬 시 학점 정보가 날라가는 문제, 계절학기를 듣지 않았는데 계절학기로 표시되는 문제 (학기선택 드롭다운 문제로 추정)

### ISSUE THREAD

**Issue by ParkGiraffe** [nnnlog/SSUrade#4]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/63358871/177936449-0081c4c6-3b4f-4ed6-8c1f-b931f31fa899.png">

처음에 학점을 불러오고 나서 리프레쉬를 실행하면 정보가 다 날라가거나, 정상적으로 불러와지거나 변칙적으로 작동합니다. (안드로이드-갤럭시노트9에서도 똑같은 문제가 발생함을 확인하였습니다.)

<img width="213" alt="image" src="https://user-images.githubusercontent.com/63358871/177936824-f00b9828-9b31-457e-9b51-029a226264cf.png">
더불어 여름학기를 듣지 않았음에도 위 사진처럼 불러오는 경우가 잦습니다.

print 문으로 getAllGrade()를 실행했을 때 getGrade()의 result를 출력해본 결과 입니다.
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/63358871/177937894-b5b55e7c-11c1-4a9f-996e-dc3095bbaa04.png">

보시면 학점리스트는 비워져 있고 석차정보만 불러오고, 다음에는 석차정보만 불러오는 패턴이 반복됩니다.
아마도 학기선택 드롭다운에서 오류가 있는 것 같습니다.

아래는 2021년도 2학기 화면에서 리프레쉬를 작동했을 때의 콘솔출력입니다.
<img width="632" alt="image" src="https://user-images.githubusercontent.com/63358871/177938587-69287342-a2dd-444d-97de-f0ed249f0f8d.png">
석차는 올바르게 가져왔지만, 과목 데이터를 전혀 가지고 오지 못했습니다. 

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/63358871/177939004-eab5d72b-71e3-437e-874d-8012e37833b5.png">
아마도 '학생 성적조회' 페이지의 '학기별 세부 성적' 섹션에서 '학기 선택'이 제대로 작동하지 않는 것으로 보입니다.

**Comment by nnnlog** [comment]
getAllGrade() 문을 실행했을 때 나온 출력값에서, 석차가 `0/0` 으로 되어 있는 학기는 실제로 수강하지 않은 학기인가요?

**Comment by ParkGiraffe** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/63358871/177981022-6b101b0c-f595-4dc8-999a-23dfa494adb9.png">
저는 계절학기를 듣지 않아서 이게 옳게 불러온 상태이고,     
   




<img width="383" alt="image" src="https://user-images.githubusercontent.com/63358871/177981326-b6a86d69-734b-466c-ba7c-adee52ab8a9d.png">
이건 잘못된 상태입니다.     
   



<img width="384" alt="image" src="https://user-images.githubusercontent.com/63358871/177981461-b44f85a3-b6c0-4d83-b757-22ee092628d5.png">
때로는 이렇게 섞여서 불러와질 때도 있습니다.




<img width="1643" alt="image" src="https://user-images.githubusercontent.com/63358871/177981662-43a62256-c004-4b5e-b428-8494d236bf81.png">
위처럼 석차가 같이 불러와질 경우도 있고, 아닌 경우도 있어서 0/0으로 되어 있는 학기가 실제로 수강하지 않은 학기라고 확답을 드리기 어려울 것 같습니다.

**Comment by nnnlog** [comment]
우선, dropdown을 선택해서 학년도/학기를 변경하는 것은 한번 검증하는 코드도 있어서 드롭다운 변경 자체는 잘 될 것 같습니다. 학년도/학기가 변경되어 성적 정보를 새로 가져올 때는 정확히 하나의 XHR 요청만 발생합니다. 이를 이용해서 XHR 요청이 종료될 때까지 대기하게 되는데, 제 생각에는 이 부분에 결함이 있는 것 같습니다.

저는 한 학기 성적 밖에 없어서 오류 재현이 어려울 것 같습니다.

USaintSession.dart의 getGrade 함수에 보시면, `showToast(...), log(...), time = ...` 으로 각각 걸린 시간을 디버깅하는 코드가 군데군데 주석 처리 되어 있습니다.
괜찮으시다면, 해당 주석 처리를 지우신 뒤, getAllGrade를 호출했을 때, 디버그 메세지가 어떻게 출력되는지 알려주시면 도움이 될 것 같습니다. (거의 모든 부분에서 `Future.delayed` 와 `Future.any` 를 사용해서 코드의 부분마다 실행 시간 제한을 걸어두었는데, 시간 제한에 걸려서 종료된 코드가 있는지 파악하고자 합니다.)

**Comment by nnnlog** [comment]
https://github.com/nnnlog/ssurade/tree/fix/get-grade
XHR 요청과 관련한 부분을 수정했습니다.
디버깅한다고 마개조해둔 코드라 UI가 조금 이상한건 무시하시고, [설정] -> [성적 정보 삭제] -> [메인 - 성적 조회]하셔도 되고, [메인 - asdf] 버튼 누르셨을 때, 모든 학기 성적 정보가 잘 불러와지는로도 확인하실 수 있습니다.

해당 브랜치에서 테스트할 때도 같은 증상이 발생하는지 확인해주시면 감사하겠습니다.

**Comment by ParkGiraffe** [comment]
@nnnlog 
get-grade branch로 실행을 해보니 버그가 해결된 상태로 아주 잘 작동합니다.
리프레쉬를 해도 오류없이 잘 불러오고, 석차정보까지 알맞게 잘 가져옵니다.

혹시 문제의 원인이 무엇이었는지 알려주실 수 있을까요?

**Comment by nnnlog** [comment]
@ParkGiraffe 
XHR 요청이 종료될 때까지 대기하는 부분과 XHR 요청에서 FINISH가 들어왔을 때, 이전에 HEADERS_RECEIVED 상태로 잡힌 XHR 요청만 처리하도록 일부 로직을 변경했습니다.

**Comment by ParkGiraffe** [comment]
버그를 해결해주셔서 감사합니다.
